version: '2'

services:
  python:
    build: ./python
    container_name: pyspark
    volumes:
      - ./JUPYTERNOTEBOOKS/:/JUPYTERNOTEBOOKS
    ports:
      - "1234:1234"
      - "8000:8000"
    command: jupyter lab --no-browser --ip=0.0.0.0 --port=1234 --allow-root