version: '2'

services:
  python:
    build: ./python
    container_name: python
    volumes:
      - ./notebooks/:/notebooks
    ports:
      - "1234:1234"
    command: jupyter lab --no-browser --ip=0.0.0.0 --port=1234 --allow-root