version: '2'

services:
  python:
    build: ./python
    restart: always
    container_name: python
    volumes:
      - ./notebooks/:/root/notebooks
    ports:
      - "1234:1234"
    environment:
      - JUPYTER_TOKEN=dlinano
    command: jupyter lab --no-browser --ip=0.0.0.0 --port=1234 --allow-root